//Class
var MeteoriteClasses = {
    'Achondrite-prim': 'Achondrites',
    'Achondrite-ung': 'Achondrites',
    'Angrite': 'Achondrites',
    'Aubrite': 'Achondrites',
    'Aubrite-an': 'Achondrites',
    'C': 'Chondrites',
    'C1/2-ung': 'Chondrites',
    'C2': 'Chondrites',
    'C2-ung': 'Chondrites',
    'C3-ung': 'Chondrites',
    'C4': 'Chondrites',
    'C4/5': 'Chondrites',
    'C4-ung': 'Chondrites',
    'C5/6-ung': 'Chondrites',
    'C6': 'Chondrites',
    'CB': 'Chondrites',
    'CBa': 'Chondrites',
    'CBb': 'Chondrites',
    'CH/CBb': 'Chondrites',
    'CH3': 'Chondrites',
    'Chondrite-fusion crust': 'Chondrites',
    'Chondrite-ung': 'Chondrites',
    'CI1': 'Chondrites',
    'CK': 'Chondrites',
    'CK3': 'Chondrites',
    'CK3.8': 'Chondrites',
    'CK3/4': 'Chondrites',
    'CK3-an': 'Chondrites',
    'CK4/5': 'Chondrites',
    'CK4-am': 'Chondrites',
    'CK5/6': 'Chondrites',
    'CK6': 'Chondrites',
    'CM1': 'Chondrites',
    'CM1/2': 'Chondrites',
    'CM2-an': 'Chondrites',
    'CM-an': 'Chondrites',
    'CO3.0': 'Chondrites',
    'CO3.1': 'Chondrites',
    'CO3.2': 'Chondrites',
    'CO3.3': 'Chondrites',
    'CO3.4': 'Chondrites',
    'CO3.5': 'Chondrites',
    'CO3.6': 'Chondrites',
    'CO3.7': 'Chondrites',
    'CO3.8': 'Chondrites',
    'CR': 'Chondrites',
    'CR1': 'Chondrites',
    'CR2-an': 'Chondrites',
    'CV2': 'Chondrites',
    'CV3-an': 'Chondrites',
    'Acapulcoite': 'Achondrites',
    'Acapulcoite/Lodranite': 'Achondrites',
    'Acapulcoite': 'Achondrites',
    'Brachinite': 'Achondrites',
    'CK4': 'Chondrites',
    'CK5': 'Chondrites',
    'CM2': 'Chondrites',
    'CO3': 'Chondrites',
    'CR2': 'Chondrites',
    'CV3': 'Chondrites',
    'Diogenite': 'Achondrites',
    'Diogenite-an': 'Achondrites',
    'Diogenite-olivine': 'Achondrites',
    'Diogenite-pm': 'Achondrites',
    'E': 'Chondrites',
    'E3': 'Chondrites',
    'E3-an': 'Chondrites',
    'E4': 'Chondrites',
    'E5': 'Chondrites',
    'E5-an': 'Chondrites',
    'E6': 'Chondrites',
    'E-an': 'Chondrites',
    'EH': 'Chondrites',
    'EH3': 'Chondrites',
    'EH3/4-an': 'Chondrites',
    'EH4': 'Chondrites',
    'EH4/5': 'Chondrites',
    'EH5': 'Chondrites',
    'EH6': 'Chondrites',
    'EH6-an': 'Chondrites',
    'EH7': 'Chondrites',
    'EH-imp melt': 'Chondrites',
    'EL3': 'Chondrites',
    'EL3/4': 'Chondrites',
    'EL4': 'Chondrites',
    'EL4/5': 'Chondrites',
    'EL5': 'Chondrites',
    'EL6': 'Chondrites',
    'EL6/7': 'Chondrites',
    'EL7': 'Chondrites',
    'Enst achon': 'Achondrites',
    'Enst achon-ung': 'Achondrites',
    'Eucrite': 'Achondrites',
    'Eucrite-an': 'Achondrites',
    'Eucrite-Mg rich': 'Achondrites',
    'Eucrite-br': 'Achondrites',
    'Eucrite-cm': 'Achondrites',
    'Eucrite-mmict': 'Achondrites',
    'Eucrite-pmict': 'Achondrites',
    'Eucrite-unbr': 'Achondrites',
    'Fusion crust': 'Achondrites',
    'H': 'Irons ',
    'H(?)4': 'Chondrites',
    'H(5?)': 'Chondrites',
    'H(L)3': 'Chondrites',
    'H(L)3-an': 'Chondrites',
    'H/L~4': 'Chondrites',
    'H/L3': 'Chondrites',
    'H/L3.5': 'Chondrites',
    'H/L3.6': 'Chondrites',
    'H/L3.7': 'Chondrites',
    'H/L3.9': 'Chondrites',
    'H/L3-4': 'Chondrites',
    'H/L4': 'Chondrites',
    'H/L4/5': 'Chondrites',
    'H/L4-5': 'Chondrites',
    'H/L5': 'Chondrites',
    'H/L6': 'Chondrites',
    'H/L6-melt rock': 'Chondrites',
    'H?': 'Chondrites',
    'H~4': 'Chondrites',
    'H~4/5': 'Chondrites',
    'H~5': 'Chondrites',
    'H~6': 'Chondrites',
    'H3': 'Chondrites',
    'H3 ': 'Chondrites',
    'H3.0': 'Chondrites',
    'H3.1': 'Chondrites',
    'H3.2': 'Chondrites',
    'H3.2-3.7': 'Chondrites',
    'H3.2-6': 'Chondrites',
    'H3.2-an': 'Chondrites',
    'H3.3': 'Chondrites',
    'H3.4': 'Chondrites',
    'H3.4/3.5': 'Chondrites',
    'H3.4-5': 'Chondrites',
    'H3.5': 'Chondrites',
    'H3.5-4': 'Chondrites',
    'H3.6': 'Chondrites',
    'H3.6-6': 'Chondrites',
    'H3.7': 'Chondrites',
    'H3.7/3.8': 'Chondrites',
    'H3.7-5': 'Chondrites',
    'H3.7-6': 'Chondrites',
    'H3.8': 'Chondrites',
    'H3.8/3.9': 'Chondrites',
    'H3.8/4': 'Chondrites',
    'H3.8-4': 'Chondrites',
    'H3.8-5': 'Chondrites',
    'H3.8-6': 'Chondrites',
    'H3.8-an': 'Chondrites',
    'H3.9': 'Chondrites',
    'H3.9/4': 'Chondrites',
    'H3.9-5': 'Chondrites',
    'H3.9-6': 'Chondrites',
    'H3/4': 'Chondrites',
    'H3-4': 'Chondrites',
    'H3-5': 'Chondrites',
    'H3-6': 'Chondrites',
    'H3-an': 'Chondrites',
    'H4': 'Chondrites',
    'H4 ': 'Chondrites',
    'H4(?)': 'Chondrites',
    'H4/5': 'Chondrites',
    'H4/6': 'Chondrites',
    'H4-5': 'Chondrites',
    'H4-6': 'Chondrites',
    'H4-an': 'Chondrites',
    'H5': 'Chondrites',
    'H5 ': 'Chondrites',
    'H5/6': 'Chondrites',
    'H5-6': 'Chondrites',
    'H5-7': 'Chondrites',
    'H5-melt breccia': 'Chondrites',
    'H6': 'Chondrites',
    'H6 ': 'Chondrites',
    'H6/7': 'Chondrites',
    'H6-melt breccia': 'Chondrites',
    'H7': 'Chondrites',
    'H-an': 'Irons',
    'H-imp melt': 'Irons',
    'H-melt rock': 'Irons',
    'H-metal': 'Irons',
    'Howardite': 'Achondrites',
    'Impact melt breccia ': 'Chondrites',
    'Iron': 'Irons',
    'Iron, IAB complex': 'Irons',
    'Iron, IAB?': 'Irons',
    'Iron, IAB-MG': 'Irons',
    'Iron, IAB-sHH': 'Irons',
    'Iron, IAB-sHL': 'Irons',
    'Iron, IAB-sLH': 'Irons',
    'Iron, IAB-sLL': 'Irons',
    'Iron, IAB-sLM': 'Irons',
    'Iron, IAB-ung': 'Irons',
    'Iron, IC': 'Irons',
    'Iron, IC-an': 'Irons',
    'Iron, IIAB': 'Irons',
    'Iron, IIAB-an': 'Irons',
    'Iron, IIC': 'Irons',
    'Iron, IID': 'Irons',
    'Iron, IID-an': 'Irons',
    'Iron, IIE': 'Irons',
    'Iron, IIE-an': 'Irons',
    'Iron, IIF': 'Irons',
    'Iron, IIG': 'Irons',
    'Iron, IIIAB': 'Irons',
    'Iron, IIIAB?': 'Irons',
    'Iron, IIIAB-an': 'Irons',
    'Iron, IIIE': 'Irons',
    'Iron, IIIE-an': 'Irons',
    'Iron, IIIF': 'Irons',
    'Iron, IVA': 'Irons',
    'Iron, IVA-an': 'Irons',
    'Iron, IVB': 'Irons',
    'Iron, ungrouped': 'Irons',
    'K': 'Chondrites',
    'K3': 'Chondrites',
    'L': 'Chondrites',
    'L(?)3': 'Chondrites',
    'L(H)3': 'Chondrites',
    'L(LL)~4': 'Chondrites',
    'L(LL)3': 'Chondrites',
    'L(LL)3.05': 'Chondrites',
    'L(LL)3.5-3.7': 'Chondrites',
    'L/LL': 'Chondrites',
    'L/LL(?)3': 'Chondrites',
    'L/LL~4': 'Chondrites',
    'L/LL~5': 'Chondrites',
    'L/LL~6': 'Chondrites',
    'L/LL3': 'Chondrites',
    'L/LL3.10': 'Chondrites',
    'L/LL3.2': 'Chondrites',
    'L/LL3.4': 'Chondrites',
    'L/LL3.6/3.7': 'Chondrites',
    'L/LL3-5': 'Chondrites',
    'L/LL3-6': 'Chondrites',
    'L/LL4': 'Chondrites',
    'L/LL4/5': 'Chondrites',
    'L/LL5v': 'Chondrites',
    'L/LL5/6': 'Chondrites',
    'L/LL5-6': 'Chondrites',
    'L/LL6': 'Chondrites',
    'L/LL6-an': 'Chondrites',
    'L/LL-melt rock': 'Chondrites',
    'L~3': 'Chondrites',
    'L~4': 'Chondrites',
    'L~5': 'Chondrites',
    'L~6': 'Chondrites',
    'L3': 'Chondrites',
    'L3.0': 'Chondrites',
    'L3.0-3.7': 'Chondrites',
    'L3.0-3.9': 'Chondrites',
    'L3.05': 'Chondrites',
    'L3.1': 'Chondrites',
    'L3.10': 'Chondrites',
    'L3.2': 'Chondrites',
    'L3.2-3.5': 'Chondrites',
    'L3.2-3.6': 'Chondrites',
    'L3.3': 'Chondrites',
    'L3.3-3.5': 'Chondrites',
    'L3.3-3.6': 'Chondrites',
    'L3.3-3.7': 'Chondrites',
    'L3.4': 'Chondrites',
    'L3.4-3.7': 'Chondrites',
    'L3.5': 'Chondrites',
    'L3.5-3.7': 'Chondrites',
    'L3.5-3.8': 'Chondrites',
    'L3.5-3.9': 'Chondrites',
    'L3.6': 'Chondrites',
    'L3.6-4': 'Chondrites',
    'L3.7': 'Chondrites',
    'L3.7/3.8': 'Chondrites',
    'L3.7-3.9': 'Chondrites',
    'L3.7-4': 'Chondrites',
    'L3.7-6': 'Chondrites',
    'L3.8': 'Chondrites',
    'L3.8-5': 'Chondrites',
    'L3.8-6': 'Chondrites',
    'L3.8-an': 'Chondrites',
    'L3.9': 'Chondrites',
    'L3.9/4': 'Chondrites',
    'L3.9-5': 'Chondrites',
    'L3.9-6': 'Chondrites',
    'L3/4': 'Chondrites',
    'L3-4': 'Chondrites',
    'L3-5': 'Chondrites',
    'L3-6': 'Chondrites',
    'L3-7': 'Chondrites',
    'L4': 'Chondrites',
    'L4 ': 'Chondrites',
    'L4/5': 'Chondrites',
    'L4-5': 'Chondrites',
    'L4-6': 'Chondrites',
    'L4-an': 'Chondrites',
    'L4-melt rock': 'Chondrites',
    'L5': 'Chondrites',
    'L5 ': 'Chondrites',
    'L5/6': 'Chondrites',
    'L5-6': 'Chondrites',
    'L6': 'Chondrites',
    'L6 ': 'Chondrites',
    'L6/7': 'Chondrites',
    'L6-melt breccia': 'Chondrites',
    'L6-melt rock': 'Chondrites',
    'L7': 'Chondrites',
    'L-imp melt': 'Chondrites',
    'LL': 'Chondrites',
    'LL(L)3': 'Chondrites',
    'LL~3': 'Chondrites',
    'LL~4': 'Chondrites',
    'LL~4/5': 'Chondrites',
    'LL~5': 'Chondrites',
    'LL~6': 'Chondrites',
    'LL<3.5': 'Chondrites',
    'LL3': 'Chondrites',
    'LL3.0': 'Chondrites',
    'LL3.00': 'Chondrites',
    'LL3.1': 'Chondrites',
    'LL3.10': 'Chondrites',
    'LL3.15': 'Chondrites',
    'LL3.2': 'Chondrites',
    'LL3.3': 'Chondrites',
    'LL3.4': 'Chondrites',
    'LL3.5': 'Chondrites',
    'LL3.6': 'Chondrites',
    'LL3.7': 'Chondrites',
    'LL3.7-6': 'Chondrites',
    'LL3.8': 'Chondrites',
    'LL3.8-6': 'Chondrites',
    'LL3.9': 'Chondrites',
    'LL3.9/4': 'Chondrites',
    'LL3/4': 'Chondrites',
    'LL3-4': 'Chondrites',
    'LL3-5': 'Chondrites',
    'LL3-6': 'Chondrites',
    'LL4': 'Chondrites',
    'LL4/5': 'Chondrites',
    'LL4/6': 'Chondrites',
    'LL4-5': 'Chondrites',
    'LL4-6': 'Chondrites',
    'LL5': 'Chondrites',
    'LL5/6': 'Chondrites',
    'LL5-6': 'Chondrites',
    'LL5-7': 'Chondrites',
    'LL6': 'Chondrites',
    'LL6 ': 'Chondrites',
    'LL6(?)': 'Chondrites',
    'LL6/7': 'Chondrites',
    'LL7': 'Chondrites',
    'LL7(?)': 'Chondrites',
    'LL-melt rock': 'Chondrites',
    'L-melt breccia': 'Chondrites',
    'L-melt rock': 'Chondrites',
    'L-metal': 'Chondrites',
    'Lodranite': 'Achondrites',
    'Lodranite-an': 'Achondrites',
    'Lunar': 'Achondrites',
    'Lunar (anorth)': 'Achondrites',
    'Lunar (bas. breccia)': 'Achondrites',
    'Lunar (bas/anor)': 'Achondrites',
    'Lunar (bas/gab brec)': 'Achondrites',
    'Lunar (basalt)': 'Achondrites',
    'Lunar (feldsp. breccia)': 'Achondrites',
    'Lunar (gabbro)': 'Achondrites',
    'Martian': 'Achondrites',
    'Martian (chassignite)': 'Achondrites',
    'Martian (nakhlite)': 'Achondrites',
    'Martian (OPX)': 'Achondrites',
    'Martian (shergottite)': 'Achondrites',
    'Mesosiderite': 'Stony Irons',
    'Mesosiderite?': 'Stony Irons',
    'Mesosiderite-A': 'Stony Irons',
    'Mesosiderite-A1': 'Stony Irons',
    'Mesosiderite-A2': 'Stony Irons',
    'Mesosiderite-A3': 'Stony Irons',
    'Mesosiderite-A4': 'Stony Irons',
    'Mesosiderite-an': 'Stony Irons',
    'Mesosiderite-B': 'Stony Irons',
    'Mesosiderite-B1': 'Stony Irons',
    'Mesosiderite-B2': 'Stony Irons',
    'Mesosiderite-B4': 'Stony Irons',
    'Mesosiderite-C': 'Stony Irons',
    'Mesosiderite-C2': 'Stony Irons',
    'Pallasite': 'Stony Irons',
    'Pallasite, PES': 'Stony Irons',
    'Pallasite, PMG': 'Stony Irons',
    'Pallasite, PMG-an': 'Stony Irons',
    'Pallasite, ungrouped': 'Stony Irons',
    'Pallasite?': 'Stony Irons',
    'R': 'Chondrites',
    'R3': 'Chondrites',
    'R3.4': 'Chondrites',
    'R3.5-6': 'Chondrites',
    'R3.6': 'Chondrites',
    'R3.7': 'Chondrites',
    'R3.8': 'Chondrites',
    'R3.8-5': 'Chondrites',
    'R3.8-6': 'Chondrites',
    'R3.9': 'Chondrites',
    'R3/4': 'Chondrites',
    'R3-4': 'Chondrites',
    'R3-5': 'Chondrites',
    'R3-6': 'Chondrites',
    'R4': 'Chondrites',
    'R4/5': 'Chondrites',
    'R5': 'Chondrites',
    'R6': 'Chondrites',
    'Relict H': 'Irons',
    'Relict iron': 'Irons',
    'Relict OC': 'Irons',
    'Stone-uncl': 'Achondrites',
    'Stone-ung': 'Achondrites',
    'Ureilite': 'Achondrites',
    'Ureilite-an': 'Achondrites',
    'Ureilite-pmict': 'Achondrites',
    'Winonaite': 'Achondrites',
    'Unknown' : 'Unknown'
};